//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classroom_Fund
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.InteropServices;

    public partial class classroom
    {
        public classroom() { }
        public classroom(byte floor_number, long responsible_person_id, short number, int capacity, bool compliance_with_safety_regulations) 
        {
            this.floor_number = floor_number;
            this.responsible_person_id = responsible_person_id;
            this.number = number;
            this.capacity = capacity;
            this.compliance_with_safety_regulations = compliance_with_safety_regulations;
        }
        public long id { get; set; }
        public byte floor_number { get; set; }
        public long responsible_person_id { get; set; }
        public short number { get; set; }
        public int capacity { get; set; }
        public bool compliance_with_safety_regulations { get; set; }
    
        public virtual floor floor { get; set; }
        public virtual person person { get; set; }
        public void Update(classroom cr)
        {
            this.floor_number = cr.floor_number;
            this.responsible_person_id = cr.responsible_person_id;
            this.number = cr.number;
            this.capacity = cr.capacity;
            this.compliance_with_safety_regulations = cr.compliance_with_safety_regulations;
        }
    }
}
