//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classroom_Fund
{
    using System;
    using System.Collections.Generic;
    
    public partial class firm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public firm()
        {
            this.act_of_renting = new HashSet<act_of_renting>();
        }
        public firm(string name, string contact_phone_number, string contact_first_name, string contact_last_name, string contact_middle_name)
        {
            this.act_of_renting = new HashSet<act_of_renting>();
            this.name = name;
            this.contact_phone_number = contact_phone_number;
            this.contact_first_name = contact_first_name;
            this.contact_last_name = contact_last_name;
            this.contact_middle_name = contact_middle_name;
        }
        public long id { get; set; }
        public string name { get; set; }
        public string contact_phone_number { get; set; }
        public string contact_first_name { get; set; }
        public string contact_last_name { get; set; }
        public string contact_middle_name { get; set; }
        public void Update(firm f)
        {
            this.name = f.name;
            this.contact_phone_number = f.contact_phone_number;
            this.contact_first_name = f.contact_first_name;
            this.contact_last_name = f.contact_last_name;
            this.contact_middle_name = f.contact_middle_name;
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<act_of_renting> act_of_renting { get; set; }
    }
}
