//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classroom_Fund
{
    using System;
    using System.Collections.Generic;
    
    public partial class floor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public floor()
        {
            this.act_of_renting = new HashSet<act_of_renting>();
            this.classroom = new HashSet<classroom>();
        }

        public floor(byte number, string department_name)
        {
            this.act_of_renting = new HashSet<act_of_renting>();
            this.classroom = new HashSet<classroom>();
            this.number = number;
            this.department_name = department_name;
        }
        public void Update(floor f)
        {
            this.number = f.number;
            this.department_name = f.department_name;
        }

        public byte number { get; set; }
        public string department_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<act_of_renting> act_of_renting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classroom> classroom { get; set; }
    }
}
