//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classroom_Fund
{
    using System;
    using System.Collections.Generic;
    
    public partial class floors_and_classrooms
    {
        public long id { get; set; }
        public byte floor_number { get; set; }
        public long responsible_person_id { get; set; }
        public short number { get; set; }
        public int capacity { get; set; }
        public bool compliance_with_safety_regulations { get; set; }
        public string department_name { get; set; }
    }
}
