//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classroom_Fund
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class classroom_fundEntities : DbContext
    {
        public classroom_fundEntities()
            : base("name=classroom_fundEntities")
        {
        }
        public classroom_fundEntities(string connectionString)
           : base(connectionString)
        {
        }


        public virtual DbSet<act_of_renting> act_of_renting { get; set; }
        public virtual DbSet<classroom> classroom { get; set; }
        public virtual DbSet<firm> firm { get; set; }
        public virtual DbSet<floor> floor { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<floors_and_classrooms> floors_and_classrooms { get; set; }
    
        public virtual int renting_price(Nullable<decimal> min_price, Nullable<decimal> max_price)
        {
            var min_priceParameter = min_price.HasValue ?
                new ObjectParameter("min_price", min_price) :
                new ObjectParameter("min_price", typeof(decimal));
    
            var max_priceParameter = max_price.HasValue ?
                new ObjectParameter("max_price", max_price) :
                new ObjectParameter("max_price", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("renting_price", min_priceParameter, max_priceParameter);
        }
    }
}
