//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Classroom_Fund
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public person()
        {
            this.classroom = new HashSet<classroom>();
        }
        public person(string first_name, string last_name, string middle_name, string phone_number, string address)
        {
            this.classroom = new HashSet<classroom>();
            this.first_name = first_name;
            this.last_name = last_name;
            this.middle_name = middle_name;
            this.phone_number = phone_number;
            this.address = address;
        }

        public long id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string middle_name { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
        public void Update(person p)
        {
            this.first_name = p.first_name;
            this.last_name = p.last_name;
            this.middle_name = p.middle_name;
            this.phone_number = p.phone_number;
            this.address = p.address;
        }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<classroom> classroom { get; set; }
    }
}
